name: Rust

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [  gh-pages ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Build book
      run: |
          python3 tools/generate_summary.py
          cat src/SUMMARY.md
          mdbook build
          python3 tools/fix_dollar_sign.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book
